import = ["/home/bruno/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 14

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "U"
mods = "Control|Shift"
